### ISSUE TITLE
Invalid wttr.in response with location Leeuwarden

### ISSUE THREAD

**Issue by MrHappy** [bjesus/wttrbar#71]
When I use location Leeuwarden I get
`{"text":"⛓️‍💥", "tooltip":"invalid wttr.in response"}`
Other location I tried seem to work. Also using Leeuwarden on the site wttr.in works fine.

**Comment by MrHappy** [comment]
The same command as you... Weird...

**Comment by bjesus** [comment]
What does `curl 'https://wttr.in/Leeuwarden?format=j1'` give you? The error you're seeing ("invalid wttr.in response") can only occur when wttr.in responses with something that isn't valid JSON. You can probably try to use `response.text()` around https://github.com/bjesus/wttrbar/blob/main/src/main.rs#L65 to see what wttr.in is returning.

**Comment by MrHappy** [comment]
The json returned by curl seems valid.
I will try the other option later today.
It's weird though that an other location works fine (and creates a json-file in tmp), but Leeuwarden does not (and does not create a file)

**Comment by MrHappy** [comment]
> What does `curl 'https://wttr.in/Leeuwarden?format=j1'` give you? The error you're seeing ("invalid wttr.in response") can only occur when wttr.in responses with something that isn't valid JSON. You can probably try to use `response.text()` around https://github.com/bjesus/wttrbar/blob/main/src/main.rs#L65 to see what wttr.in is returning.

How would I use `response.text()`. I do not know rust...

**Comment by bjesus** [comment]
It seems to be some kind of wttr.in caching issue: https://github.com/chubin/wttr.in/blob/355a515b1f9ea31b193cb9c1d3cef5e5dff07de9/internal/processor/processor.go#L208

I don't think wttrbar can do much about it, unfortunately. You can try to [customize the user agent header](https://webscraping.ai/faq/reqwest/how-do-i-customize-the-user-agent-string-in-reqwest) to see if it bypasses the cache issue somehow, but since I cannot reproduce this it's impossible for me to say.

**Comment by MrHappy** [comment]
If it a caching issue, it would be on my system I would guess.
Where do I find the caching of wttr.in/wttrbar? 'Cause I have not found it...

**Comment by MrHappy** [comment]
Issue seems to have resolved itself.
